export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
//admin
export const GET_ADMIN_ERRORS = "GET_ADMIN_ERRORS";
export const ADMIN_LOADING = "ADMIN_LOADING";
export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";
export const SET_PLAN_WITH_CARD = "SET_PLAN_WITH_CARD";

export const REGISTER_INFO = "SET_REGISTER_USER";
export const SET_EMAIL_VALID = "SET_EMAIL_VALID";
export const SET_REGISTER_NEXT_STEP = "SET_REGISTER_NEXT_STEP";
export const SET_REGISTER_BACK_STEP = "SET_REGISTER_BACK_STEP";
export const SET_LAST_EVENT_ID = "SET_LAST_EVENT_ID";
export const SET_FIXTURE_EVENT = "SET_FIXTURE_EVENT";
export const SET_LAST_EVENT_DATE = "SET_LAST_EVENT_DATE";
export const SET_PLAYERLIST = "SET_PLAYERLIST";
export const SET_TOP_WEEK = "SET_TOP_WEEK";